### ISSUE TITLE
Pages Meta Data Updates

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/challenges-and-prizes#2114]
### User Story
As a site user, in order to find relevant Challenge.gov pages and navigate the site content effectively, I would like the page titles and descriptions to accurately reflect the page content.

**Acceptance Criteria:**

- [x] The following changes are applies to page titles, og:titles, meta descriptions and og:descriptions
- [x] Home page:
  - [x] Title: Challenge.gov
  - [x] Description: Challenge.gov is the official government website supporting prize challenges and prize competitions that are sponsored by the US federal government.  Here federal agencies provide prize awards to public citizens and entities who solve problems and develop innovations.
- [x] Pages & Posts:
  - [x] Title: [page title] | Challenge.gov
    - [x] [page title] is provided by content editors in markdown
  - [x] Description: Challenge.gov is the official government website supporting prize challenges and prize competitions that are sponsored by the US federal government.  Here federal agencies provide prize awards to public citizens and entities who solve problems and develop innovations.

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
~- [ ] Code is organized appropriately~
- [x] Any known trade offs are documented in the associated GH issue
~- [ ] Code is documented, modules, shared functions, etc.~
~- [ ] Automated testing has been added or updated in response to changes in this PR~
- [x] The feature is smoke tested to confirm it meets requirements
~- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks~
~- [ ] PR that changes or adds UI~
~  - [ ] include a screenshot of the WAVE report for the altered pages~
~  - [ ] Confirm changes were validated for mobile responsiveness~
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
~- [ ] Automate accessibility tests passed~
~- [ ] Build process and deployment is automated and repeatable~
~- [ ] Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [x] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [ ] Windows/Chrome
  - [ ] Windows/Edge
  - [ ] Mac/Chrome
  - [ ] Mac/Safari
  - [ ] iOS/Safari
- [x] AC review (Renata)
- [x] Deploy to production (production-like environment for eval capability) (dev team)
- [x] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by jairoanaya** [comment]
@r-bartlett-gsa this feature is on staging ready for testing.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya This is ready to go live.
